# Dockerfile.base
FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libatlas-base-dev \
    libgl1-mesa-glx \
    python3-dev \ 
 && apt-get clean && rm -rf /var/lib/apt/lists/*
